version: '3.8'

services:
  jedi-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////app/data/jedi_agent.db
      - VECTOR_DB_PATH=/app/data/vector_db
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=INFO
      - DEBUG=true
      # These should be set in your .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - LOCAL_LLM_BASE_URL=${LOCAL_LLM_BASE_URL}
    env_file:
      - .env
    volumes:
      # Mount source code for hot reloading
      - ./app:/app/app
      - ./ui:/app/ui
      - ./main.py:/app/main.py
      - ./requirements.txt:/app/requirements.txt
      - ./requirements-minimal.txt:/app/requirements-minimal.txt
      # Persistent data volumes  
      - jedi_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    ports:
      - "8001:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
      - PORT=3000
      - GENERATE_SOURCEMAP=false
    volumes:
      # Mount source code for hot reloading
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      # Exclude node_modules from being overwritten
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - jedi-agent

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  jedi_data: